version: '3.0'

services:
  diyHue:
    image: diyhue/core:latest
    # This makes for more convienient naming, but only allows one instance of the image
    container_name: diyHue
    restart: unless-stopped

    environment:
      # Uncomment to enable debug mode
      # DEBUG: true
      # IP and MAC are only needed for running diyHue in the bridge network
      IP: 172.31.156.239
      MAC: 12:34:56:78:90
    volumes:
      - /mnt/hue-emulator/export:/opt/hue-emulator/export
    ports:
      - '80:80'
      - '443:443'
      - '1900:1900/udp'
      - '2100:2100/udp'
      - '1982:1982/udp'
    # Alternatively, you can activate host mode by uncommenting the line below and removing all ports and the env vars above
    # network_mode: "host"
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000/tcp"
    environment:
      - TZ=Europe/London
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/dat
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    ports: 
      - "8123:8123"
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - /opt/mosquitto:/mosquitto
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
